[build]
  command = "python3 build_netlify.py"
  publish = "public"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  minify = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/franchise"
  to = "/franchise.html"
  status = 200

[[redirects]]
  from = "/partners"
  to = "/partners.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200
